### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x94

### ISSUE THREAD

**Issue by dbrw** [wsdjeg/SpaceVim#1004]
## Expected behavior, english is recommended
SpaceVim starts without error message. My error message was like bellow:
```
function provider#python#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 1 was closed by the client
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 67: ordinal not in range(128)
Logged from file base.py, line 113
Failed to load python host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
Press ENTER or type command to continue
```

After pressing `enter`, I can use the editor just fine. But it is so annoying to see the error and press `enter` each time I start nvim.

## Environment Information
- OS: Archlinux with kernel 4.13.12-1-ARCH
- vim version: n/a
- neovim version: 0.2.1

## The reproduce ways from Vim starting (Required!)
run `nvim` on terminal

## Output of the ':SPDebugInfo!'
```viml
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.6.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimQuickFix', 'HelpDescribe']
g:spacevim_default_indent = 4
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'arrow'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = [['lumiliet/vim-twig', {'on_ft': 'twig'}], ['vim-scripts/php.vim-html-enhanced', {'on_ft': 'php'}], ['jwalton512/vim-blade', {'on_ft': 'php'}], ['adriaanzon/vim-texto
bj-blade-directive', {'on_ft': 'php'}], ['joonty/vdebug'], ['joonty/vim-phpunitqf'], ['vim-pandoc/vim-pandoc'], ['vim-pandoc/vim-pandoc-syntax'], ['vim-pandoc/vim-pandoc-after'], ['veloce/vim-be
hat', {'on_ft': 'feature'}]]
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 4
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 80
g:spacevim_enable_debug = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_key_frequency = 0
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_lint_on_save = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_keep_server_alive = 1
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'ind
ents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'nvim', 'linux', 'lang#php', 'incsearch', 'lang#javascrip
t', 'lang#vim', 'lang#python', 'lang#tex', 'shell', 'colorscheme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/dim/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_relativenumber = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_realtime_leader_guide = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_github_username = ''
g:spacevim_leader_guide_hspace = 5
g:spacevim_src_root = 'E:\sources\'
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_leader_guide_hspace = 5
g:spacevim_src_root = 'E:\sources\'
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_custom_color_palette = []
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_language = ''
g:spacevim_enable_vimfiler_gitstatus = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: Linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:29:37] [ Info ] Skip glob configration of SpaceVim
```

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

### custom config
```viml
" Dark powered mode of SpaceVim, generated by SpaceVim automatically.
let g:spacevim_enable_debug = 1
let g:spacevim_realtime_leader_guide = 1
let g:spacevim_max_column = 80
let g:spacevim_default_indent = 4
call SpaceVim#layers#load('lang#go')
call SpaceVim#layers#load('lang#php')
call SpaceVim#layers#load('incsearch')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#vim')
call SpaceVim#layers#load('lang#python')
call SpaceVim#layers#load('lang#tex')
call SpaceVim#layers#load('shell')   
call SpaceVim#layers#load('incsearch')   
call SpaceVim#layers#load('autocomplete')   
let g:spacevim_enable_vimfiler_welcome = 1
let g:deoplete#auto_complete_delay = 150
let g:spacevim_enable_tabline_filetype_icon = 1
let g:spacevim_enable_os_fileformat_icon = 1
let g:spacevim_buffer_index_type = 1
let g:indentLine_enabled = 0
let g:spacevim_buffer_index_type = 4
let g:spacevim_windows_index_type = 1
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'
if has('python3')
    let g:ctrlp_map = ''
    nnoremap <silent> <C-p> :Denite file_rec<CR>
endif
let g:clang2_placeholder_next = ''
let g:clang2_placeholder_prev = ''
let g:spacevim_custom_plugins = [
    \ ['lumiliet/vim-twig', {'on_ft' : 'twig'}],
    \ ['vim-scripts/php.vim-html-enhanced', {'on_ft' : 'php'}],
    \ ['jwalton512/vim-blade', {'on_ft' : 'php'}],
    \ ['adriaanzon/vim-textobj-blade-directive', {'on_ft' : 'php'}],
    \ ['joonty/vdebug'],
    \ ['joonty/vim-phpunitqf'],
    \ ['vim-pandoc/vim-pandoc'],
    \ ['vim-pandoc/vim-pandoc-syntax'],
    \ ['vim-pandoc/vim-pandoc-after'],
    \ ['veloce/vim-behat', {'on_ft' : 'feature'}],
    \ ]
set nowrap
set ignorecase
```

## Screenshots

no screenshot

**Comment by Shougo** [comment]
Hm.
SpaceVim logging seems to  send the wrong bytes.

**Comment by dbrw** [comment]
Is there anything I can do?
I cannot reproduce the bug on my other computer. I've re-install the SpaceVim, all the plugins on `.cache/vimfiles/repos/github`, also re-install neovim.
All doesn't works on this computer.

**Comment by Shougo** [comment]
You can disable the logging.

```vim
let g:spacevim_enable_debug = 0
```

**Comment by dbrw** [comment]
unfortunately, after changing the `spacevim_enable_debug` variable as bellow:
```viml
let g:spacevim_enable_debug = 0
```
on `~/.SpaceVim.d/init.vim`, the error does not go away. Could it because of some plugin that SpaceVim brings along?

I tried running `nvim -u NONE` and the error goes away, so it couldn't be neovim error.

**Comment by Shougo** [comment]
I think @wsdjeg knows the method to disable the logs.

**Comment by wsdjeg** [comment]
SpaceVim do not use python script to log info.

Logged from file base.py, line 113 


this should comes from a plugin.

**Comment by Shougo** [comment]
Hm...

@dbrw You should create the minimal configuration.

**Comment by dbrw** [comment]
I deleted my `init.vim` file to create a fresh config but the error does not dissapear.

So I started logging using `NVIM_PYTHON_LOG_FILE`, got some interesting line like bellow:
```log
File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/event_loop/base.py", line 113, in send
```
the complete log is on https://gist.github.com/dbrw/2ea61abc8cdaedaf2781b25a7a2d3f3a#file-log_py2_script-L70

both `python2-neovim` and `python-neovim` packages is up to date.
any suggestion?

**Comment by Shougo** [comment]
It is SpaceVim error?
Can you reproduce error without SpaceVim?

You should create the minimal init.vim without SpaceVim and report the issue in neovim.

**Comment by Shougo** [comment]
> I tried running nvim -u NONE and the error goes away, so it couldn't be neovim error.

> I deleted my init.vim file to create a fresh config but the error does not dissapear.

What is the fresh config?

**Comment by dbrw** [comment]
> It is SpaceVim error?

I think it's related to SpaceVim.

> Can you reproduce error without SpaceVim?

I can't reproduce the error without SpaceVim.
When I delete SpaceVim, I can run `nvim` from terminal without error.

> What is the fresh config?

Here is the fresh SpaceVim config
```viml
" Dark powered mode of SpaceVim, generated by SpaceVim automatically.
let g:spacevim_enable_debug = 1
let g:spacevim_realtime_leader_guide = 1
call SpaceVim#layers#load('incsearch')
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#elixir')
call SpaceVim#layers#load('lang#go')
call SpaceVim#layers#load('lang#haskell')
call SpaceVim#layers#load('lang#java')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#perl')
call SpaceVim#layers#load('lang#php')
call SpaceVim#layers#load('lang#python')
call SpaceVim#layers#load('lang#rust')
call SpaceVim#layers#load('lang#swig')
call SpaceVim#layers#load('lang#tmux')
call SpaceVim#layers#load('lang#vim')
call SpaceVim#layers#load('lang#xml')
call SpaceVim#layers#load('shell')   
call SpaceVim#layers#load('tools#screensaver')
let g:spacevim_enable_vimfiler_welcome = 1
let g:spacevim_enable_debug = 1
let g:deoplete#auto_complete_delay = 150
let g:spacevim_enable_tabline_filetype_icon = 1
let g:spacevim_enable_statusline_display_mode = 0
let g:spacevim_enable_os_fileformat_icon = 1
let g:spacevim_buffer_index_type = 1
let g:neomake_vim_enabled_makers = []
if executable('vimlint')
    call add(g:neomake_vim_enabled_makers, 'vimlint') 
endif
if executable('vint')
    call add(g:neomake_vim_enabled_makers, 'vint') 
endif
if has('python3')
    let g:ctrlp_map = ''
    nnoremap <silent> <C-p> :Denite file_rec<CR>
endif
let g:clang2_placeholder_next = ''
let g:clang2_placeholder_prev = ''
```

I think I found the culprit, It was this line:
```viml
call SpaceVim#layers#load('lang#c')
```
when I remove that line, the error goes away. I am okay without C layer, since I rarely working on C, so I will keep it commented.

Possibly outdated or crashed plugins on C layer?

**Comment by wsdjeg** [comment]
@dbrw can you try to remove 

https://github.com/SpaceVim/SpaceVim/blob/version-control/autoload/SpaceVim/layers/lang/c.vim#L50

and to see if this error still exist?
