### ISSUE TITLE
error with deoplete and deoplete-clang2

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1077]
```log
[deoplete] Traceback (most recent call last):                                                                                                          
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 474, in on_event     
[deoplete]     source.on_event(context)                                                                                                                
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 151, in on_event      
[deoplete]     cmd, flags = self.build_flags(context)                                                                                                  
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 505, in build_flags   
[deoplete]     flags = self.get_clang_flags(lang) + flags                                                                                              
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 226, in get_clang_flag
s                                                                                                                                                      
[deoplete]     stdout = self.call_clang([], clang_flags, True)                                                                                         
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 321, in call_clang    
[deoplete]     elif self.debug_enabled and stderr.strip():                                                                                             
[deoplete] AttributeError: 'Source' object has no attribute 'debug_enabled'                                                                            
[deoplete] Exception during clang2.on_event for event 'Init': 'Source' object has no attribute 'debug_enabled'.  Use :messages for error details.  
```

in SpaceVim deoplete is loaded on InsertEnter event, deoplete is loaded when vim startup.

**Comment by wsdjeg** [comment]
@Shougo Hi, I think this issue is diu to the latest commits of deoplete.

**Comment by wsdjeg** [comment]
`git reset --hard HEAD~8` fix this issue in the root of deoplete repo, I think maybe some commit break the compatibility.

**Comment by Shougo** [comment]
https://github.com/tweekmonster/deoplete-clang2/pull/23

Hm.

I will patch the problem.

**Comment by Shougo** [comment]
@wsdjeg I have fixed the error in the latest deoplete.
Please check it.

**Comment by wsdjeg** [comment]
@Shougo Thanks, it works well for me. :+1:
