### ISSUE TITLE
Get errors when open js file

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1098]
```

Error detected while processing function <SNR>255_JobHandler:
line    7:
import-js error: module.js:544     throw err;     ^  Error: Cannot find module '/home/wsdjeg/.npm-packages/lib/node_modules/import-js/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node'     at Function.Module._resolveFilename (module.js:542:15)     at Function.Module._load (module.js:472:25)     at Module.require (module.js:585:17)     at require (internal/module.js:11:18)     at Object.<anonymous> (/home/wsdjeg/.npm-packages/lib/node_modules/import-js/node_modules/sqlite3/lib/sqlite3.js:4:15)     at Module._compile (module.js:641:30)     at Object.Module._extensions..js (module.js:652:10)     at Module.load (module.js:560:32)     at tryModuleLoad (module.js:503:12)     at Function.Module._load (module.js:495:3) 
Error detected while processing function <SNR>255_JobHandler:
line    7:
import-js error: 
E21: Cannot make changes, 'modifiable' is off
```

but I have installed the mode via `npm install -g import-js`

**Comment by wsdjeg** [comment]
ok, got it:

It is : 

```vim
  if has('win32') || has('win64')
    let s:job_executable='importjs.cmd'
  else
    let s:job_executable='importjs'
  endif

  " neovim
  if exists("*jobstart")
    let s:job = jobstart([s:job_executable, 'start', '--parent-pid', getpid()], s:callbacks)
  endif

  " vim
  if exists("*job_start")
    let s:job=job_start([s:job_executable, 'start', '--parent-pid', getpid()], {
          \'exit_cb': 'importjs#JobExit',
          \})

    let g:ImportJSChannel=job_getchannel(s:job)
  endif

```

```
wsdjeg@archlinux:~$ importjs  start --parent-pid 10639
module.js:544
    throw err;
    ^

Error: Cannot find module '/home/wsdjeg/.npm-packages/lib/node_modules/import-js/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wsdjeg/.npm-packages/lib/node_modules/import-js/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

**Comment by opoei** [comment]
Ran into this issue myself. A red flag for me was that my version under `.npm-packages/lib/node_modules/import-js/node_modules/sqlite3/lib/binding/` had a version mismatch with importjs expectations. ( I had a bunch of globally installed node packages). I removed the offending packages and the error is now suppressed. Re-Run SPUpdate and importjs should work as expected.

**Comment by wsdjeg** [comment]
Thanks
