### ISSUE TITLE
Error message "[deoplete@yarp] Job is dead" when editing a C file

### ISSUE THREAD

**Issue by jetm** [wsdjeg/SpaceVim#1190]
## Expected behavior, English is recommended

No error expected while editing C file and C completion should work.

_As a note_: C completion was working before and this error message started to appears recently. I could not figure out in which point of the history it started failing.
I am using SpaceVim in dev branch and Git hash: 8cbd007 Merge pull request #1186 from SpaceVim/job_improve.

## Environment Information
- OS: Arch Linux
- vim version: 
```
IM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 19 2017 20:38:43)
Included patches: 1-1415
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    +tcl/dyn
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl/dyn          +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua/dyn           +ruby/dyn          +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       -xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.26/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm
```

## The reproduce ways from Vim starting (Required!)

Start with a clean C file and press `i` for insert text or `o` for a new line:
```shell
$ vim hello.c
```

This error will appear:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
[deoplete@yarp] Traceback (most recent call last):
[deoplete@yarp]   File "/home/javier/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 487, in on_event
[deoplete@yarp]     source.on_event(context)
[deoplete@yarp]   File "/home/javier/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/file.py", line 33, in on_event
[deoplete@yarp]     self.vim.options['isfname'])
[deoplete@yarp]   File "/usr/lib/python3.6/site-packages/neovim/api/common.py", line 81, in __getitem__
[deoplete@yarp]     return self._get(key)
[deoplete@yarp]   File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 130, in request
[deoplete@yarp]     res = self._session.request(name, *args, **kwargs)
[deoplete@yarp]   File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 93, in request
[deoplete@yarp]     raise IOError('EOF')
[deoplete@yarp] OSError: EOF
[deoplete@yarp] During handling of the above exception, another exception occurred:
[deoplete@yarp] Traceback (most recent call last):
[deoplete@yarp]   File "/home/javier/.cache/vimfiles/repos/github.com/SpaceVim/nvim-yarp/pythonx/yarp.py", line 33, in <module>
[deoplete@yarp]     module_obj = importlib.import_module(module)
[deoplete@yarp]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
[deoplete@yarp]     return _bootstrap._gcd_import(name[level:], package, level)
[deoplete@yarp]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[deoplete@yarp]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[deoplete@yarp]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[deoplete@yarp]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[deoplete@yarp]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[deoplete@yarp]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[deoplete@yarp]   File "/home/javier/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 49, in <module>
[deoplete@yarp]     global_deoplete = Deoplete(vim)
[deoplete@yarp]   File "/home/javier/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 43, in __init__
[deoplete@yarp]     self.on_event(context)
[deoplete@yarp]   File "/home/javier/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 491, in on_event
[deoplete@yarp]     source_name, context['event'], exc))
[deoplete@yarp]   File "/home/javier/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/util.py", line 120, in error_tb
[deoplete@yarp]     error(vim, str(line))
[deoplete@yarp]   File "/home/javier/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/util.py", line 113, in error
[deoplete@yarp]     return vim.err_write('[deoplete] ' + string + '\n')
[deoplete@yarp]   File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 306, in err_write
[deoplete@yarp]     return self.request('nvim_err_write', msg, **kwargs)
[deoplete@yarp]   File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 130, in request
[deoplete@yarp]     res = self._session.request(name, *args, **kwargs)
[deoplete@yarp]   File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 93, in request
[deoplete@yarp]     raise IOError('EOF')
[deoplete@yarp] OSError: EOF
[deoplete@yarp] Job is dead. cmd=['python3', '/home/javier/.cache/vimfiles/repos/github.com/SpaceVim/nvim-yarp/pythonx/yarp.py', '127.0.0.1:41355', 2, 'deoplete']
```

### SpaceVim Options :
```viml
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']
g:spacevim_default_indent = 2
g:spacevim_custom_plugins = [['sheerun/vim-polyglot', {'merged': 0}], ['vitalk/vim-shebang'], ['octol/vim-cpp-enhanced-highlight', {'on_ft': 'c'}], ['igankevich/mesonic'], ['benmills/vimux'], ['junegunn/fzf.vim'], ['kergoth/vim-bitbake'], ['vivien/vim-linux-coding-style']]
g:spacevim_buffer_index_type = 0
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_error_symbol = '✖'
g:spacevim_enable_key_frequency = 0
g:spacevim_max_column = 80
g:spacevim_enable_insert_leader = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_dein_installed = 1
g:spacevim_enable_neomake = 0
g:spacevim_relativenumber = 1
g:spacevim_realtime_leader_guide = 1
g:spacevim_github_username = ''
g:spacevim_denite_leader = 'F'
g:spacevim_enable_cursorline = 1
g:spacevim_leader_guide_vertical = 0
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'version control info', 'hunks']
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.6.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme = 'onedark'
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_plugin_manager = 'dein'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_debug = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_checkinstall = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_enable_ycm = 0
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_neobundle_installed = 0
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_enable_powerline_fonts = 1
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_vimfiler_welcome = 0
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_guifont = ''
g:spacevim_language = ''
g:spacevim_plugin_bundle_dir = '/home/javier/.cache/vimfiles/'
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_lint_on_the_fly = 1
g:spacevim_debug_level = 1
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_statusline_separator = 'arrow'
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_enable_ale = 1
g:spacevim_custom_color_palette = []
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_auto_disable_touchpad = 1
g:spacevim_lint_on_save = 1
g:spacevim_keep_server_alive = 1
g:spacevim_unite_leader = 'f'
g:spacevim_disabled_plugins = []
g:spacevim_info_symbol = '🛈'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'VersionControl', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#banner', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'vim', 'linux', 'lang#c', 'colorscheme']
g:spacevim_enable_neocomplcache = 0
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_leader_guide_hspace = 5
g:spacevim_windows_index_type = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 800
OS: Linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :
```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [08:59:40] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
```

**Comment by wsdjeg** [comment]
Yeah, I can reproduce it now, but I can not fix it now.

**Comment by wsdjeg** [comment]
This error happens when I add this plugin:

```
call add(plugins, ['bbchung/clighter8', { 'if' : has('python')}])
```

**Comment by jetm** [comment]
Hmmm, I can reproduce it without 'bbchung/clighter8' plugin. I believe this was before the installation of that plugin.

**Comment by wsdjeg** [comment]
@jetm This is the last commit which is works well with c file.

https://github.com/SpaceVim/SpaceVim/tree/fix_1190

**Comment by wsdjeg** [comment]
ohh,  deoplete-clang2 does not support vim, see:

https://github.com/tweekmonster/deoplete-clang2/blob/master/plugin/clang2.vim#L1-L3

**Comment by wsdjeg** [comment]
@jetm If I remove this three lines, This errors is gone. but I am not sure if deoplete-clang2 support vim8.

**Comment by jetm** [comment]
@wsdjeg: Yes, the issue is with deoplete-clang2 plugin. No using this plugin it works fine. Thank you.

There is another issue I have found. I have this setting based in the [C layer documentation](https://github.com/SpaceVim/SpaceVim/blob/dev/docs/layers/lang/c.md): 

```viml
call SpaceVim#layers#load('lang#c',
  \ {
  \   'enable_libclang' : 1,
  \   'libclang_path' : '/usr/lib/libclang.so',
  \ }
  \ )
```
I was expecting this setting will use _zchee/deoplete-clang_, instead of _tweekmonster/deoplete-clang2_. But in the [c.vim code](https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/layers/lang/c.vim#L91) it says _use_libclang_. I have tested it and with this works as expected, use _zchee/deoplete-clang_:
```viml
call SpaceVim#layers#load('lang#c',
  \ {
  \   'use_libclang' : 1,
  \   'libclang_path' : '/usr/lib/libclang.so',
  \ }
  \ )
```

I would make a PR, but don't which is preferred either _use_libclang_ or  _enable_libclang_.

**Comment by wsdjeg** [comment]
I have fix this issue, please update spacevim, and I just send a PR to deoplete-clang2

**Comment by wsdjeg** [comment]
@jetm Thanks I will fix the code. the doc will be kept.
