### ISSUE TITLE
python3 error under windows

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#1462]
## The reproduce ways from Vim starting (Required!)

always

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

```
PS C:\tools\neovim\Neovim\bin> .\nvim.exe
function SpaceVim#util#haspy3lib[2]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 1 was closed by the client
Traceback (most recent call last):^M
  File "<string>", line 1, in <module>^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\site-packages\neovim\__init__.py", line 70, in start_host^M
    session = stdio_session()^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 37, in stdio_session^M
    return session('stdio')^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 18, in session^M
    loop = EventLoop(transport_type, *args, **kwargs)^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\site-packages\neovim\msgpack_rpc\event_loop\base.py", line 92, in __init__^M
    raise e^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\site-packages\neovim\msgpack_rpc\event_loop\base.py", line 89, in __init__^M
    getattr(self, '_connect_{}'.format(transport_type))(*args)^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 95, in _connect_stdio^M
    self._loop.run_until_complete(coroutine)^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 467, in run_until_complete^M
    return future.result()^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 294, in result^M
    raise self._exception^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 240, in _step^M
    result = coro.send(None)^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1114, in connect_write_pipe^M
    transport = self._make_write_pipe_transport(pipe, protocol, waiter)^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\proactor_events.py", line 423, in _make_write_pipe_transport^M
    sock, protocol, waiter, extra)^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\proactor_events.py", line 316, in __init__^M
    self._read_fut = self._loop._proactor.recv(self._sock, 16)^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\windows_events.py", line 425, in recv^M
    self._register_with_iocp(conn)^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\windows_events.py", line 606, in _register_with_iocp^M
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)^M
OSError: [WinError 6] <be><e4><b1><fa><ce><de><a1><a3>^M
Exception ignored in: <bound method _ProactorBasePipeTransport.__del__ of <_ProactorWritePipeTransport closing fd=1>>^M
Traceback (most recent call last):^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\proactor_events.py", line 96, in __del__^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\proactor_events.py", line 84, in close^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 573, in call_soon^M
  File "C:\Users\Matrix\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 357, in _check_closed^M
RuntimeError: Event loop is closed^M
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
function SpaceVim#end[86]..SpaceVim#plugins#load[4]..<SNR>37_load_plugins[3]..<SNR>37_getLayerPlugins[3]..SpaceVim#layers#tools#plugins[47]..<SNR>7_has[3]..provider#python#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):E475: Invalid argument: Channel id must be a positive integer
Failed to load python host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
Press ENTER or type command to continue
```

**Comment by deepseeksss** [comment]
my init.vim has config:
```
let g:python_host_prog = 'C:/Python27/python.exe'
let g:python3_host_prog = 'C:/Users/Matrix/AppData/Local/Programs/Python/Python35/python.exe'
```

**Comment by wsdjeg** [comment]
does this issue happend without SpaceVim.

**Comment by deepseeksss** [comment]
without spacevim, the has('python3') return 1

**Comment by wsdjeg** [comment]
what is `echo g:python_host_prog` and `echo g:python3_host_prog`?

and what is checkhealth,

**Comment by deepseeksss** [comment]
![default](https://user-images.githubusercontent.com/1751829/36946615-6ab572d2-1ffa-11e8-96a7-e943aa1db497.png)

how to echo ???

![default](https://user-images.githubusercontent.com/1751829/36946621-7e7dd70a-1ffa-11e8-9cea-3785cf49c876.png)

**Comment by wsdjeg** [comment]
@Matrix-Zhang so where do you add:

```
let g:python_host_prog = 'C:/Python27/python.exe'
let g:python3_host_prog = 'C:/Users/Matrix/AppData/Local/Programs/Python/Python35/python.exe'
```

**Comment by deepseeksss** [comment]
$HOME/SpaceVim.d/init.vim

**Comment by wsdjeg** [comment]
sorry, I can not reproduce it, in windows, I think you can use gvim instead.

**Comment by deepseeksss** [comment]
i don't like gvim at all, the problem occurs on my both home and work computer

**Comment by Shougo** [comment]
https://github.com/neovim/python-client/issues/306

**Comment by deepseeksss** [comment]
@Shougo 3ks

**Comment by deepseeksss** [comment]
after update pip3's neovim, it's ok
