### ISSUE TITLE
Error occurred while editing in c/cpp files.

### ISSUE THREAD

**Issue by VyronLee** [wsdjeg/SpaceVim#1588]
## Expected behavior, english is recommend

Autocomplete should work as expected.

## Environment Information

- OS: OSX
- vim version: -
- neovim version: 0.2.2
- SpaceVim version: 0.8.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

### SpaceVim Options :

```viml
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.8.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']
g:spacevim_default_indent = 4
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_language_specific_leader = 1
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'nord'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = [['arcticicestudio/nord-vim'], ['nathanaelkane/vim-indent-guides']]
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 1
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_smartclose = 'q'
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_enable_ale = 0
g:spacevim_enable_insert_leader = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 80
g:spacevim_enable_debug = 1
g:spacevim_enable_key_frequency = 0
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 16
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_unite_leader = '\f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_statusline_separator = 'arrow'
g:spacevim_project_rooter_automatically = 1
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = [['floobits-neovim']]
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/Users/vyronlee/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_relativenumber = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_keep_server_alive = 1
g:spacevim_snippet_engine = 'ultisnips'
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang']
g:spacevim_enable_cursorcolumn = 0
g:spacevim_github_username = 'VyronLee'
g:spacevim_leader_guide_hspace = 5
g:spacevim_realtime_leader_guide = 0
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 0
g:spacevim_filetype_icons = {}
g:spacevim_plugin_name = 'Unite-sources'
g:spacevim_enable_cursorline = 1
g:spacevim_custom_color_palette = []
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_language = ''
g:spacevim_filemanager = 'nerdtree'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_enable_vimfiler_gitstatus = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.2.2_1/bin/nvim)
version: 800
OS: OSX
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [23:44:06] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [23:44:06] [ Info ] Find project root('.git/',''):/Users/vyronlee/Workspace/ldb/.git/
[ SpaceVim ] [23:44:06] [ Info ] change to root:/Users/vyronlee/Workspace/ldb
[ SpaceVim ] [23:44:06] [ Info ] Find project root('.git/','/Users/vyronlee/Workspace/ldb/Startify'):/Users/vyronlee/Workspace/ldb/.git/
[ SpaceVim ] [23:44:06] [ Info ] change to root:/Users/vyronlee/Workspace/ldb
[ SpaceVim ] [23:44:10] [ Info ] Find project root('.git/','/Users/vyronlee/Workspace/ldb/src/ldb.cpp'):/Users/vyronlee/Workspace/ldb/.git/
[ SpaceVim ] [23:44:10] [ Info ] change to root:/Users/vyronlee/Workspace/ldb
```
## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

[![asciicast](https://asciinema.org/a/eoHCrjTRpWCoDlAsnjqBl0lZg.png)](https://asciinema.org/a/eoHCrjTRpWCoDlAsnjqBl0lZg)

**Comment by Shougo** [comment]
I cannot reproduce the error.
It is reproduce-able with deoplete.nvim only without SpaceVim?

**Comment by VyronLee** [comment]
@Shougo Forgive my late for the reply. I have tried several times using the vimrc below

```
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/home/vyronlee/.cache/vimfiles/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/home/vyronlee/.cache/vimfiles')
  call dein#begin('/home/vyronlee/.cache/vimfiles')

  " Let dein manage dein
  " Required:
  call dein#add('/home/vyronlee/.cache/vimfiles/repos/github.com/Shougo/dein.vim')

    call dein#add('Shougo/deoplete.nvim')
    if !has('nvim')
      call dein#add('roxma/nvim-yarp')
      call dein#add('roxma/vim-hug-neovim-rpc')
    endif

    call dein#add('tweekmonster/deoplete-clang2')

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

let g:deoplete#enable_at_startup = 1

let g:deoplete#sources#clang#autofill_neomake = 1
let g:neomake_c_enabled_makers = ["clang"]
let g:neomake_cpp_enabled_makers = ["clang"]

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
```

and there is nothing wrong. Autocomplete works fine.

I notice that when I remove all  `'on_event' : 'InsertEnter'` in the file within spacevim
 https://github.com/SpaceVim/SpaceVim/blob/f01a649b7046204e5806de6ae7a6d36129702111/autoload/SpaceVim/layers/autocomplete.vim#L31-L40
and things will get right again.

Maybe there is something conflict with deoplete in these plugins?

**Comment by Shougo** [comment]
Hm.  You can add `on_event` in your vimrc.
Please test it.

**Comment by VyronLee** [comment]
ok, I add the plugins listed above, and now vimrc looks like this

```
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/home/vyronlee/.cache/vimfiles/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/home/vyronlee/.cache/vimfiles')
  call dein#begin('/home/vyronlee/.cache/vimfiles')

  " Let dein manage dein
  " Required:
  call dein#add('/home/vyronlee/.cache/vimfiles/repos/github.com/Shougo/dein.vim')

    call dein#add('Shougo/deoplete.nvim')
    if !has('nvim')
      call dein#add('roxma/nvim-yarp')
      call dein#add('roxma/vim-hug-neovim-rpc')
    endif

    """""""""""""""""""""""""""""""""""""""""
    " New plugins for testing.
    call dein#add('tweekmonster/deoplete-clang2')
    call dein#add('honza/vim-snippets', { 'on_event' : 'InsertEnter', 'loadconf_before' : 1})
    call dein#add('Shougo/neco-syntax', { 'on_event' : 'InsertEnter'})
    call dein#add('ujihisa/neco-look', { 'on_event' : 'InsertEnter'})
    call dein#add('Shougo/context_filetype.vim', { 'on_event' : 'InsertEnter'})
    call dein#add('Shougo/neoinclude.vim', { 'on_event' : 'InsertEnter'})
    call dein#add('Shougo/neosnippet-snippets')
    call dein#add('Shougo/neopairs.vim', { 'on_event' : 'InsertEnter'})
    call dein#add('Raimondi/delimitMate')
    """"""""""""""""""""""""""""""""""""""""""

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

let g:deoplete#enable_at_startup = 1

let g:deoplete#sources#clang#autofill_neomake = 1
let g:neomake_c_enabled_makers = ["clang"]
let g:neomake_cpp_enabled_makers = ["clang"]

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
```

When I open a file and type some chars, errors occur
[![asciicast](https://asciinema.org/a/ZyomFocO7N6pV5sVgfNkEvSpn.png)](https://asciinema.org/a/ZyomFocO7N6pV5sVgfNkEvSpn)

**Comment by Shougo** [comment]
OK.  Please minimize the configuration more.
And it must be cpp files?

**Comment by VyronLee** [comment]
No, use c projects for testing will get the same result. Here is the vimrc only using deoplete-clang2 and neoinclude.vim that I can minimize the most:

```
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/home/vyronlee/.cache/vimfiles/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/home/vyronlee/.cache/vimfiles')
  call dein#begin('/home/vyronlee/.cache/vimfiles')

  " Let dein manage dein
  " Required:
  call dein#add('/home/vyronlee/.cache/vimfiles/repos/github.com/Shougo/dein.vim')

    call dein#add('Shougo/deoplete.nvim')
    if !has('nvim')
      call dein#add('roxma/nvim-yarp')
      call dein#add('roxma/vim-hug-neovim-rpc')
    endif

    """""""""""""""""""""""""""""""""""""""""
    " New plugins for testing.
    call dein#add('tweekmonster/deoplete-clang2')

    " call dein#add('honza/vim-snippets', { 'on_event' : 'InsertEnter', 'loadconf_before' : 1})
    " call dein#add('Shougo/neco-syntax', { 'on_event' : 'InsertEnter'})
    " call dein#add('ujihisa/neco-look', { 'on_event' : 'InsertEnter'})
    " call dein#add('Shougo/context_filetype.vim', { 'on_event' : 'InsertEnter'})
    call dein#add('Shougo/neoinclude.vim', { 'on_event' : 'InsertEnter'})
    " call dein#add('Shougo/neosnippet-snippets')
    " call dein#add('Shougo/neopairs.vim', { 'on_event' : 'InsertEnter'})
    " call dein#add('Raimondi/delimitMate')

    " call dein#add('Shougo/neosnippet.vim', { 'on_event' : 'InsertEnter',
          " \ 'on_ft' : 'neosnippet',
          " \ 'loadconf' : 1,
          " \ 'on_cmd' : 'NeoSnippetEdit'})
    """"""""""""""""""""""""""""""""""""""""""

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

let g:deoplete#enable_at_startup = 1

let g:deoplete#sources#clang#autofill_neomake = 1
let g:neomake_c_enabled_makers = ["clang"]
let g:neomake_cpp_enabled_makers = ["clang"]

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
```

and the result testing in project [luadist/lua](https://github.com/LuaDist/lua):
[![asciicast](https://asciinema.org/a/O33qavIlVrU0jwN1gzOfW3sm5.png)](https://asciinema.org/a/O33qavIlVrU0jwN1gzOfW3sm5)

when I remove neoinclude.vim and enable other plugins, no errors occur.

**Comment by Shougo** [comment]
deoplete-clang2 plugin is needed?
It does not occur for other plugin?
Ex: deoplete-clangx

> when I remove neoinclude.vim and enable other plugins, no errors occur.

I must reproduce the problem in my environment.
Please upload the test project to reproduce it.

**Comment by VyronLee** [comment]
I will test it with deoplete-clangx later.

You can just use the project [Luadist/Lua(https://github.com/LuaDist/lua)](https://github.com/LuaDist/lua) and my [vimrc](https://gist.github.com/VyronLee/20f8a8b9d5201f9eda990299bb6a2430)  to reproduce the problem.

`CD` to lua project and use `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .` to generate the `compile_commands.json` and then open a c file, input some chars and errors will occur.

**Comment by Shougo** [comment]
I have reproduced the error.
But I cannot reproduce the problem with deoplete-clangx.

**Comment by Shougo** [comment]
```
2018-04-14 19:44:01,167 [ERROR @ base_events.py:default_exception_handler:1265] 29966 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /usr/lib/python3.6/asyncio/base_events.py:1166> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached',)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1191, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 858, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
```

Hm.  The error occurred.

**Comment by Shougo** [comment]
Reason: https://github.com/tweekmonster/deoplete-clang2/issues/30#issuecomment-381320864

**Comment by Shougo** [comment]
You should use deoplete-clangx instead.

**Comment by VyronLee** [comment]
Since #1619 deoplete-clang2 has been replaced by deoplete-clangx. It works fine now!

Thanks for your great plugin!

**Comment by VyronLee** [comment]
Close.
