### ISSUE TITLE
denite errors on misnamed `file_recd` when using SPC f f to find file

### ISSUE THREAD

**Issue by BretFisher** [wsdjeg/SpaceVim#1597]
I think a [recent commit of this line](https://github.com/SpaceVim/SpaceVim/blob/c7b85d5f56dd8108ae72c4316161247a2370afa6/autoload/SpaceVim/layers/denite.vim#L33) is giving error due to extra `d` on the end of `file_rec`

## Expected behavior, english is required
with denite enabled, `SPC f f` should work

## The reproduce ways from Vim starting (Required!)
1. Latest master on SpaceVim
2. Enable denite in init.vim
3. Use `SPC f f`
4. Receive error

```
[denite] Traceback (most recent call last):
[denite]   File "/Users/bret/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/__init__.py", line 29, in star
t
[denite]     return ui.start(args[0], args[1])
[denite]   File "/Users/bret/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 71, in st
art
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/bret/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 119, in _
start
[denite]     self.init_denite()
[denite]   File "/Users/bret/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 657, in i
nit_denite
[denite]     self._denite.on_init(self._context)
[denite]   File "/Users/bret/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/denite.py", line 172, in on_in
it
[denite]     raise NameError('Source "' + name + '" is not found.')
[denite] NameError: Source "file_recd" is not found.
[denite] Please execute :messages command.
```

## Debug info

```
SpaceVim layers:

+ VersionControl:           loaded          https://spacevim.org/layers/VersionControl
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete
- chat:                 not loaded          https://spacevim.org/layers/chat
+ checkers:                 loaded          https://spacevim.org/layers/checkers
- chinese:              not loaded          https://spacevim.org/layers/chinese
- colorscheme:          not loaded          https://spacevim.org/layers/colorscheme
+ core/banner:              loaded          no exists
+ core/statusline:          loaded          no exists
+ core/tabline:             loaded          no exists
+ core:                     loaded          no exists
- cscope:               not loaded          https://spacevim.org/layers/cscope
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp
- debug:                not loaded          https://spacevim.org/layers/debug
+ denite:                   loaded          https://spacevim.org/layers/denite
+ edit:                     loaded          no exists
- exprfold:             not loaded          no exists
+ format:                   loaded          no exists
- fzf:                  not loaded          https://spacevim.org/layers/fzf
- games:                not loaded          no exists
+ git:                      loaded          https://spacevim.org/layers/git
+ github:                   loaded          https://spacevim.org/layers/github
+ incsearch:                loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          no exists
- lang/c:               not loaded          https://spacevim.org/layers/lang/c
- lang/clojure:         not loaded          no exists
- lang/crystal:         not loaded          no exists
- lang/csharp:          not loaded          https://spacevim.org/layers/lang/csharp
- lang/dart:            not loaded          https://spacevim.org/layers/lang/dart
- lang/elixir:          not loaded          https://spacevim.org/layers/lang/elixir
+ lang/go:                  loaded          https://spacevim.org/layers/lang/go
- lang/haskell:         not loaded          https://spacevim.org/layers/lang/haskell
+ lang/html:                loaded          https://spacevim.org/layers/lang/html
- lang/java:            not loaded          https://spacevim.org/layers/lang/java
+ lang/javascript:          loaded          https://spacevim.org/layers/lang/javascript
+ lang/json:                loaded          no exists
- lang/julia:           not loaded          no exists
- lang/kotlin:          not loaded          no exists
- lang/lisp:            not loaded          https://spacevim.org/layers/lang/lisp
- lang/lua:             not loaded          https://spacevim.org/layers/lang/lua
+ lang/markdown:            loaded          https://spacevim.org/layers/lang/markdown
- lang/ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml
- lang/perl:            not loaded          no exists
+ lang/php:                 loaded          https://spacevim.org/layers/lang/php
- lang/pony:            not loaded          no exists
- lang/ps1:             not loaded          no exists
- lang/puppet:          not loaded          no exists
+ lang/python:              loaded          https://spacevim.org/layers/lang/python
- lang/ruby:            not loaded          https://spacevim.org/layers/lang/ruby
- lang/rust:            not loaded          no exists
- lang/scala:           not loaded          no exists
- lang/sh:              not loaded          no exists
- lang/solidity:        not loaded          no exists
- lang/swig:            not loaded          no exists
+ lang/tmux:                loaded          no exists
- lang/toml:            not loaded          no exists
- lang/typescript:      not loaded          https://spacevim.org/layers/lang/typescript
+ lang/vim:                 loaded          https://spacevim.org/layers/lang/vim
- lang/xml:             not loaded          no exists
- lang:                 not loaded          no exists
- leaderf:              not loaded          https://spacevim.org/layers/leaderf
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell
- tags:                 not loaded          https://spacevim.org/layers/tags
- tmux:                 not loaded          no exists
- tools/dash:           not loaded          https://spacevim.org/layers/tools/dash
- tools/screensaver:    not loaded          no exists
- tools:                not loaded          https://spacevim.org/layers/tools
+ ui:                       loaded          https://spacevim.org/layers/ui
- unite:                not loaded          https://spacevim.org/layers/unite
- vim:                  not loaded          no exists
```

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
oh，Thanks！I am not at my laptop，would you like to open an PR？

**Comment by BretFisher** [comment]
sure.  PR on the way.
