### ISSUE TITLE
Use denite layer RecursionError

### ISSUE THREAD

**Issue by longhaiqwe** [wsdjeg/SpaceVim#1810]
## Expected behavior, english is required

Use denite layer RecursionError

## The reproduce ways from Vim starting (Required!)

use gtags to generate  GTAGS, GPATH, GRTAGS, then use SPC m g r/d to jump to the definitions or references. Maybe it will work well a few time, but when I use it more， the error will occur.

## Debug info
```
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_api_json_true = v:null
g:spacevim_auto_disable_touchpad = 1
g:spacevim_autocomplete_method = 'neocomplete'
g:spacevim_background = 'dark'
g:spacevim_buffer_index_type = 4
g:spacevim_checkinstall = 1
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_custom_color_palette = []
g:spacevim_custom_plugins = []
g:spacevim_debug_level = 1
g:spacevim_default_indent = 2
g:spacevim_dein_installed = 1
g:spacevim_denite_leader = '\f'
g:spacevim_disabled_plugins = []
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_enable_cursorline = 1
g:spacevim_enable_debug = 0
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_language_specific_leader = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_neomake = 1
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_ycm = 0
g:spacevim_error_symbol = '✖'
g:spacevim_expand_tab = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_filetype_icons = {}
g:spacevim_force_global_config = 0
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_github_username = ''
g:spacevim_guicolors = 1
g:spacevim_guifont = ''
g:spacevim_hiddenfileinfo = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_keep_server_alive = 1
g:spacevim_language = ''
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_leader_guide_flatten = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_leader_guide_max_size = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_leader_guide_vertical = 0
g:spacevim_lint_on_save = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_max_column = 120
g:spacevim_neobundle_installed = 0
g:spacevim_plugin_bundle_dir = '/home/longhai/.cache/vimfiles/'
g:spacevim_plugin_manager = 'dein'
g:spacevim_plugin_manager_max_processes = 16
g:spacevim_plugin_name = 'vim-python-pep8-indent'
g:spacevim_project_rooter_automatically = 1
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang']
g:spacevim_realtime_leader_guide = 1
g:spacevim_relativenumber = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_sidebar_width = 30
g:spacevim_simple_mode = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_spacevim_automatic_update = 1
g:spacevim_spacevim_max_column = 70
g:spacevim_src_root = 'E:\sources\'
g:spacevim_statusline_display_mode = 0
g:spacevim_statusline_inactive_separator = 'bar'
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_statusline_separator = 'nil'
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_unite_leader = '\f'
g:spacevim_version = '0.8.0-dev'
g:spacevim_vim_help_language = 'en'
g:spacevim_vim_plug_installed = 0
g:spacevim_vimcompatible = 1
g:spacevim_warning_symbol = '⚠'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_windows_index_type = 0
g:spacevim_windows_leader = ''
g:spacevim_windows_smartclose = 0
```

## Screenshots

```
[denite] Traceback (most recent call last):
[denite]   File "<string>", line 9, in _temporary_scope
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 127, in _start
[denite]     self.init_buffer()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 151, in init_buffer
[denite]     self._prev_wininfo = self._get_wininfo()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 246, in _get_wininfo
[denite]     wininfo = self._vim.call('getwininfo', self._vim.call('win_getid'))[0]
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 62, in call
[denite]     return reform_bytes(self.Function(name)(*args))
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 18, in reform_bytes
[denite]     return list(map(reform_bytes, value))
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15, in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 18, in reform_bytes
[denite]     return list(map(reform_bytes, value))
[denite]   File "/home/longhai/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 13, in reform_bytes
[denite]     elif isinstance(value, (dict, vim.Dictionary, vim.Options)):
[denite] RecursionError: maximum recursion depth exceeded in __instancecheck__
[denite] Please execute :messages command.
```

**Comment by longhaiqwe** [comment]
vim+unite and neovim+denite is OK. Now I choose neovim+denite, better than vim+unite. : )

**Comment by wsdjeg** [comment]
@longhaiqwe sorry, I do not know why denite prints such error in vim8.  does denite other's key bindings works well?

**Comment by wsdjeg** [comment]
Oh, you should use `SPC m g c` to generate database before using other key binding in tags layer.
