### ISSUE TITLE
LSP layer errors

### ISSUE THREAD

**Issue by johnnypea** [wsdjeg/SpaceVim#1948]
## Expected behavior, english is required
**lsp** layer shouldn't be throwing any errors.

## The reproduce ways from Vim starting (Required!)
Insert mode in PHP files throws these errors:
```
[deoplete] Traceback (most recent call last):                                                                                                        
  File "/Users/johnnypea/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/child.py", line 250, in _gather_async_results
                                                                                                                                                     
    async_candidates = source.gather_candidates(context)                                                                                             
  File "/Users/johnnypea/.cache/vimfiles/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", l
ine 29, in gather_candidates                                                                                                                         
    candidates = outputs[0].get("result", [])                                                                                                        
AttributeError: 'list' object has no attribute 'get'                                                                                                 
Error from LanguageClient: AttributeError("'list' object has no attribute 'get'").  Use :messages / see above for error details.                     
[deoplete] Traceback (most recent call last):                                                                                                        
  File "/Users/johnnypea/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/child.py", line 250, in _gather_async_results
                                                                                                                                                     
    async_candidates = source.gather_candidates(context)                                                                                             
  File "/Users/johnnypea/.cache/vimfiles/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", l
ine 29, in gather_candidates                                                                                                                         
    candidates = outputs[0].get("result", [])                                                                                                        
AttributeError: 'list' object has no attribute 'get'                                                                                                 
Error from LanguageClient: AttributeError("'list' object has no attribute 'get'").  Use :messages / see above for error details.                     
[deoplete] Too many errors from "LanguageClient". This source is disabled until Neovim is restarted.
```

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.3.0
- SpaceVim version: 0.9.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

### SpaceVim Options :

```viml
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_api_json_true = v:null
g:spacevim_auto_disable_touchpad = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_autocomplete_parens = 1
g:spacevim_background = 'dark'
g:spacevim_buffer_index_type = 4
g:spacevim_checkinstall = 1
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_custom_color_palette = []
g:spacevim_custom_plugins = []
g:spacevim_debug_level = 1
g:spacevim_default_indent = 2
g:spacevim_disabled_plugins = []
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_enable_cursorline = 1
g:spacevim_enable_debug = 0
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_language_specific_leader = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_neomake = 1
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_statusline_mode = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_ycm = 0
g:spacevim_error_symbol = '‚úñ'
g:spacevim_expand_tab = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_filetype_icons = {}
g:spacevim_force_global_config = 0
g:spacevim_gitcommit_issue_icon = 'ÔÅ™'
g:spacevim_gitcommit_pr_icon = 'Óú¶'
g:spacevim_github_username = ''
g:spacevim_guifont = ''
g:spacevim_hiddenfileinfo = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_info_symbol = '‚ìò'
g:spacevim_keep_server_alive = 1
g:spacevim_language = ''
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_leader_guide_flatten = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_leader_guide_max_size = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_leader_guide_vertical = 0
g:spacevim_lint_on_save = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_max_column = 120
g:spacevim_plugin_bundle_dir = '/Users/johnnypea/.cache/vimfiles/'
g:spacevim_plugin_manager = 'dein'
g:spacevim_plugin_manager_processes = 16
g:spacevim_plugin_name = 'php-language-server'
g:spacevim_project_rooter_automatically = 1
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
g:spacevim_realtime_leader_guide = 1
g:spacevim_relativenumber = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_sidebar_width = 30
g:spacevim_simple_mode = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_statusline_separator = 'arrow'
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_version = '0.9.0-dev'
g:spacevim_vim_help_language = 'en'
g:spacevim_vimcompatible = 0
g:spacevim_warning_symbol = '‚ö†'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_windows_index_type = 0
g:spacevim_windows_leader = 's'
g:spacevim_windows_smartclose = 'q'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.3.0/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:40:10] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [12:40:13] [ Info ] Find project root('.git/','/Users/johnnypea/Development/wp-example/wp-content/mu-plugins/taxonomies.php'):/Users/johnnypea/Development/wp-example/.git/
[ SpaceVim ] [12:40:13] [ Info ] change to root:/Users/johnnypea/Development/wp-example
```

**Comment by wsdjeg** [comment]
Maybe it is an bug of autozimu/LanguageClient-neovim, report it on it's issue stracker is better.

**Comment by johnnypea** [comment]
@wsdjeg I tested it without SpaceVim with this configuration and it was working:
```
" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

" (Optional) Multi-entry selection UI.
Plug 'junegunn/fzf'

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

" Initialize plugin system
call plug#end()

" Required for operations modifying multiple buffers like rename.
set hidden

let g:LanguageClient_serverCommands = {
    \ 'php': ['php', '~/.cache/vimfiles/repos/github.com/felixfbecker/php-language-server/bin/php-language-serveria.php'],
    \ }

nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
```
Does your layer actually install the same version of autozimu/LanguageClient-neovim:
```
    call add(plugins, ['autozimu/LanguageClient-neovim',
          \ { 'merged': 0, 'if': has('python3') }])
```
as
```
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
```
?

Thanks.

**Comment by haringsrob** [comment]
I think indeed the `bash install.sh` step is missing.
I went to `.cache/vimfiles/repos/github.com/autozimu/LanguageClient-neovim` and ran it manually to make it work.

**Comment by wsdjeg** [comment]
@haringsrob Thanks, I will fix lsp layer.
