### ISSUE TITLE
SPC f r  missing

### ISSUE THREAD

**Issue by hongjiujing** [wsdjeg/SpaceVim#1974]
## Expected behavior, english is required
works as expected.
## The reproduce ways from Vim starting (Required!)

I have git pull to update spacevim, but once SPC f r,  I cannot see "open a recent file" in cmd list. Why?

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

https://asciinema.org/a/xVnD3BED1frGURB8ZVnaib3xm

**Comment by hongjiujing** [comment]
## Expected behavior, english is recommend

## Environment Information

- OS: linux
- vim version: 8.1.20
- neovim version: -
- SpaceVim version: 0.9.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

## The reproduce ways from Vim starting (Required!)

## Output of the `:SPDebugInfo!`

### SpaceVim Options :

```viml
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_api_json_true = v:null
g:spacevim_auto_disable_touchpad = 1
g:spacevim_autocomplete_method = 'asyncomplete'
g:spacevim_autocomplete_parens = 1
g:spacevim_buffer_index_type = 1
g:spacevim_checkinstall = 1
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_custom_color_palette = []
g:spacevim_custom_plugins = []
g:spacevim_debug_level = 1
g:spacevim_default_indent = 2
g:spacevim_disabled_plugins = []
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_enable_cursorline = 1
g:spacevim_enable_debug = 1
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_language_specific_leader = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_neomake = 1
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_statusline_mode = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_ycm = 0
g:spacevim_error_symbol = '✖'
g:spacevim_expand_tab = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_filetype_icons = {}
g:spacevim_force_global_config = 0
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_github_username = ''
g:spacevim_guifont = ''
g:spacevim_hiddenfileinfo = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_keep_server_alive = 1
g:spacevim_language = ''
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_leader_guide_flatten = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_leader_guide_max_size = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_leader_guide_vertical = 0
g:spacevim_lint_on_save = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_max_column = 120
g:spacevim_plugin_bundle_dir = '/home/jiujin/.cache/vimfiles/'
g:spacevim_plugin_manager = 'dein'
g:spacevim_plugin_manager_processes = 16
g:spacevim_plugin_name = 'vimshell.vim'
g:spacevim_project_rooter_automatically = 1
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'pom.xml', 'package.json']
g:spacevim_realtime_leader_guide = 1
g:spacevim_relativenumber = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_sidebar_width = 30
g:spacevim_simple_mode = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_statusline_separator = 'arrow'
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_version = '0.9.0-dev'
g:spacevim_vim_help_language = 'en'
g:spacevim_vimcompatible = 0
g:spacevim_warning_symbol = '⚠'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_windows_index_type = 0
g:spacevim_windows_leader = 's'
g:spacevim_windows_smartclose = 'q'
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.basic)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:55:58] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [16:55:59] [ Info ] Find project root('.git/',''):/workb/bdrepo/kernel_imx/.git/
[ SpaceVim ] [16:55:59] [ Info ] change to root:/workb/bdrepo/kernel_imx
[ SpaceVim ] [16:55:59] [ Info ] Find project root('.git/','/workb/bdrepo/kernel_imx/drivers/media/Startify'):/workb/bdrepo/kernel_imx/.git/
[ SpaceVim ] [16:55:59] [ Info ] change to root:/workb/bdrepo/kernel_imx
[ SpaceVim ] [17:00:09] [ Info ] Find project root('.git/','/workb/bdrepo/kernel_imx/drivers/media/platform/mxc/capture/earlycamera_rvc.c'):/workb/bdrepo/kernel_imx/.git/
[ SpaceVim ] [17:00:09] [ Info ] change to root:/workb/bdrepo/kernel_imx
[ SpaceVim ] [17:15:18] [ Info ] Find project root('.git/','/workb/bdrepo/kernel_imx/vimfiler:default'):/workb/bdrepo/kernel_imx/.git/
[ SpaceVim ] [17:15:18] [ Info ] change to root:/workb/bdrepo/kernel_imx
```
## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

**Comment by wsdjeg** [comment]
do you load a fuzzy layer? in SpaceVim we have 5 fuzzy finder layer, ( unite, ctrlp, denite, fzf, leaderf), select the one you like.
![2018-07-25-20 48 11](https://user-images.githubusercontent.com/13142418/43202178-570b23da-904d-11e8-9548-4a239c27eec9.png)

**Comment by hongjiujing** [comment]
## Expected behavior, english is recommend

## Environment Information

- OS: linux
- vim version: 8.1.20
- neovim version: -
- SpaceVim version: 0.9.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

## The reproduce ways from Vim starting (Required!)

## Output of the `:SPDebugInfo!`

### SpaceVim Options :

```viml
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_api_json_true = v:null
g:spacevim_auto_disable_touchpad = 1
g:spacevim_autocomplete_method = 'asyncomplete'
g:spacevim_autocomplete_parens = 1
g:spacevim_buffer_index_type = 1
g:spacevim_checkinstall = 1
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_custom_color_palette = []
g:spacevim_custom_plugins = []
g:spacevim_debug_level = 1
g:spacevim_default_indent = 2
g:spacevim_disabled_plugins = []
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_enable_cursorline = 1
g:spacevim_enable_debug = 1
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_language_specific_leader = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_neomake = 1
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_statusline_mode = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_ycm = 0
g:spacevim_error_symbol = '✖'
g:spacevim_expand_tab = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_filetype_icons = {}
g:spacevim_force_global_config = 0
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_github_username = ''
g:spacevim_guifont = ''
g:spacevim_hiddenfileinfo = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_keep_server_alive = 1
g:spacevim_language = ''
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_leader_guide_flatten = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_leader_guide_max_size = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_leader_guide_vertical = 0
g:spacevim_lint_on_save = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_max_column = 120
g:spacevim_plugin_bundle_dir = '/home/jiujin/.cache/vimfiles/'
g:spacevim_plugin_manager = 'dein'
g:spacevim_plugin_manager_processes = 16
g:spacevim_plugin_name = 'vimshell.vim'
g:spacevim_project_rooter_automatically = 1
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'pom.xml', 'package.json']
g:spacevim_realtime_leader_guide = 1
g:spacevim_relativenumber = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_sidebar_width = 30
g:spacevim_simple_mode = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_statusline_separator = 'arrow'
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_version = '0.9.0-dev'
g:spacevim_vim_help_language = 'en'
g:spacevim_vimcompatible = 0
g:spacevim_warning_symbol = '⚠'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_windows_index_type = 0
g:spacevim_windows_leader = 's'
g:spacevim_windows_smartclose = 'q'
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.basic)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:55:58] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [16:55:59] [ Info ] Find project root('.git/',''):/workb/bdrepo/kernel_imx/.git/
[ SpaceVim ] [16:55:59] [ Info ] change to root:/workb/bdrepo/kernel_imx
[ SpaceVim ] [16:55:59] [ Info ] Find project root('.git/','/workb/bdrepo/kernel_imx/drivers/media/Startify'):/workb/bdrepo/kernel_imx/.git/
[ SpaceVim ] [16:55:59] [ Info ] change to root:/workb/bdrepo/kernel_imx
[ SpaceVim ] [17:00:09] [ Info ] Find project root('.git/','/workb/bdrepo/kernel_imx/drivers/media/platform/mxc/capture/earlycamera_rvc.c'):/workb/bdrepo/kernel_imx/.git/
[ SpaceVim ] [17:00:09] [ Info ] change to root:/workb/bdrepo/kernel_imx
[ SpaceVim ] [17:15:18] [ Info ] Find project root('.git/','/workb/bdrepo/kernel_imx/vimfiler:default'):/workb/bdrepo/kernel_imx/.git/
[ SpaceVim ] [17:15:18] [ Info ] change to root:/workb/bdrepo/kernel_imx
```
## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

**Comment by hongjiujing** [comment]
how to check if load a fuzzy layer?

**Comment by hongjiujing** [comment]
after enable denite , sometimes SPC f r will fail.

[denite] Traceback (most recent call last):
[denite]   File "<string>", line 9, in _temporary_scope
[denite]   File "/home/jiujin/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 
71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/jiujin/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 
127, in _start
[denite]     self.init_buffer()
[denite]   File "/home/jiujin/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 
151, in init_buffer
[denite]     self._prev_wininfo = self._get_wininfo()
[denite]   File "/home/jiujin/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 
247, in _get_wininfo
[denite]     wininfo = self._vim.call('getwininfo', self._vim.call('win_getid'))[0]
[denite]   File "/home/jiujin/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 62,
 in call
[denite]     return reform_bytes(self.Function(name)(*args))
[denite]   File "/home/jiujin/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 18,
 in reform_bytes
[denite]     return list(map(reform_bytes, value))
[denite]   File "/home/jiujin/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15,
 in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/jiujin/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15,
 in <dictcomp>
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()
[denite]   File "/home/jiujin/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 15,
 in reform_bytes
[denite]     reform_bytes(k): reform_bytes(v) for k, v in value.items()

**Comment by wsdjeg** [comment]
@hongjiujing It should be a bug of your vim evn, please update denite and vim.
