### ISSUE TITLE
Error with vext package

### ISSUE THREAD

**Issue by rachmadaniHaryono** [wsdjeg/SpaceVim#1985]
## Expected behavior, english is required
- no error when starting spacevim
## The reproduce ways from Vim starting (Required!)
- create python3 virtualenv
- install following package `vext==0.7.0` `vext.gi==0.7.0`
- start spacevim (neovim)
- following error will printed
```python
function SpaceVim#util#haspy3lib[2]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[13]..provider#Poll, line 4
Vim(if):ch 4 was closed by the client
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/q/envs/Comix/lib/python3.6/site-packages/vext/gatekeeper/__init__.py", line 204, in load_module
    raise ImportError("No module named %s" % modulename)
ImportError: No module named neovim
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
```
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.0
- SpaceVim version: 0.9.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

### SpaceVim Options :

```viml
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_api_json_true = v:null
g:spacevim_auto_disable_touchpad = 0
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_autocomplete_parens = 1
g:spacevim_automatic_update = 0
g:spacevim_buffer_index_type = 0
g:spacevim_checkinstall = 1
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_custom_color_palette = []
g:spacevim_custom_plugins = []
g:spacevim_debug_level = 1
g:spacevim_default_indent = 2
g:spacevim_disabled_plugins = ['vim-import-js']
g:spacevim_enable_ale = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_enable_cursorline = 1
g:spacevim_enable_debug = 0
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_language_specific_leader = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_neomake = 1
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_statusline_mode = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_ycm = 0
g:spacevim_error_symbol = '✖'
g:spacevim_expand_tab = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_filetype_icons = {}
g:spacevim_force_global_config = 0
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_github_username = 'rachmadaniHaryono'
g:spacevim_guifont = ''
g:spacevim_hiddenfileinfo = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_info_symbol = 'i'
g:spacevim_keep_server_alive = 1
g:spacevim_language = ''
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_leader_guide_flatten = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_leader_guide_max_size = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_leader_guide_vertical = 0
g:spacevim_lint_on_save = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_max_column = 120
g:spacevim_plugin_bundle_dir = '/home/q/.cache/vimfiles/'
g:spacevim_plugin_manager = 'dein'
g:spacevim_plugin_manager_processes = 16
g:spacevim_plugin_name = 'vim-signify'
g:spacevim_project_rooter_automatically = 1
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json']
g:spacevim_realtime_leader_guide = 1
g:spacevim_relativenumber = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_sidebar_width = 30
g:spacevim_simple_mode = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_statusline_separator = 'arrow'
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_version = '0.9.0-dev'
g:spacevim_vim_help_language = 'en'
g:spacevim_vimcompatible = 0
g:spacevim_warning_symbol = '⚠'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_windows_index_type = 0
g:spacevim_windows_leader = 's'
g:spacevim_windows_smartclose = ''
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [04:45:55] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [04:45:55] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [04:46:42] [ Info ] Find project root('.git/',''):/home/q/git/Comix/.git/
[ SpaceVim ] [04:46:42] [ Info ] change to root:/home/q/git/Comix
[ SpaceVim ] [04:46:43] [ Info ] change to root:/home/q/git/Comix
```

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by rachmadaniHaryono** [comment]
i create this issue because there is no issue related to vext package.

install neovim on that virtualenv will fix it, but that kinda strange because i expect when `g:python_host_prog` and `g:python3_host_prog` is already configured, neovim package should load from that.

also this is the actual package list on the virtualenv 

```
backcall==0.1.0
decorator==4.3.0
gobject==0.1.0
greenlet==0.4.14
ipython==6.4.0
ipython-genutils==0.2.0
jedi==0.12.1
msgpack==0.5.6
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.4
Pillow==5.2.0
prompt-toolkit==1.0.15
ptyprocess==0.6.0
pycairo==1.17.1
Pygments==2.2.0
ruamel.yaml==0.15.44
simplegeneric==0.8.1
six==1.11.0
traitlets==4.3.2
vext==0.7.0
vext.gi==0.7.0
wcwidth==0.1.7
```

**Comment by wsdjeg** [comment]
@rachmadaniHaryono what is the value of `g:python_host_prog` and `g:python3_host_prog`?

**Comment by rachmadaniHaryono** [comment]
```
let g:python_host_prog='/home/q/envs/neovim2/bin/python'
let g:python3_host_prog='/home/q/envs/neovim3/bin/python'
```

**Comment by wsdjeg** [comment]
in SpaceVim, we use `:py` command before loading custom config, so when first time to use `:py` command, neovim do not know your python_host_prog. how about support a environment variable? for example:

`$PYTHON_HOST_PROG` and `$PYTHON3_HOST_PROG`?

**Comment by rachmadaniHaryono** [comment]
both env variable is empty

**Comment by wsdjeg** [comment]
I have start a new PR about this issue.

**Comment by xiuliren** [comment]
BTW, the environment variable setting of `PYTHON3_HOST_PROG` is not in documentation?

**Comment by wsdjeg** [comment]
it is in the faq page.
