### ISSUE TITLE
deoplete error after uninstalling SpaceVim

### ISSUE THREAD

**Issue by raddevon** [wsdjeg/SpaceVim#269]
## Environment Information
- OS: macOS 10.12.3 (16D32)
- neovim version: 0.1.7

## The reproduce ways from Vim starting (Required!)
After installing and then uninstalling SpaceVim, I get an error whenever I try to type in insert mode.

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

```
error caught in async handler 'deoplete_auto_completion_begin [{'next_input': '', 'omni__omnifunc': 'tern#Complete', 'input': 'dasdf', 'filetypes': ['javascript'], 'dict__dictionary': '', 'f
iletype': 'javascript', 'keyword_patterns': '[a-zA-Z_][a-zA-Z@0-9_À-ÿ$]*', 'position': [0, 9, 6, 0], 'bufvars': {}, 'changedtick': 7, 'sources': [], 'bufname': 'functions/getPostContent/inde
x.js', 'custom': {'_': {}}, 'runtimepath': '/Users/raddevon/.config/nvim,/Users/raddevon/.config/nvim/plugged/javascript-libraries-syntax.vim/,/Users/raddevon/.config/nvim/plugged/vim-js-ind
ent/,/Users/raddevon/.config/nvim/plugged/yajs.vim/,/Users/raddevon/.config/nvim/plugged/vim-mustache-handlebars/,/Users/raddevon/.config/nvim/plugged/emmet-vim/,/Users/raddevon/.config/nvim
/plugged/vim-commentary/,/Users/raddevon/.config/nvim/plugged/vim-surround/,/Users/raddevon/.config/nvim/plugged/matchit.zip/,/Users/raddevon/.config/nvim/plugged/auto-pairs/,/Users/raddevon
/.config/nvim/plugged/vim-closetag/,/Users/raddevon/.config/nvim/plugged/oceanic-next/,/Users/raddevon/.config/nvim/plugged/vim-airline/,/Users/raddevon/.config/nvim/plugged/vim-indent-guide
s/,/Users/raddevon/.config/nvim/plugged/deoplete.nvim/,/Users/raddevon/.config/nvim/plugged/tern_for_vim/,/Users/raddevon/.fzf/,/Users/raddevon/.config/nvim/plugged/fzf.vim/,/Users/raddevon/
.config/nvim/plugged/vim-ags/,/etc/xdg/nvim,/Users/raddevon/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/Cellar/neovim/0.1.7/share/nvim/runtime,/usr/shar
e/nvim/site/after,/usr/local/share/nvim/site/after,/Users/raddevon/.local/share/nvim/site/after,/etc/xdg/nvim/after,/Users/raddevon/.config/nvim/plugged/javascript-libraries-syntax.vim/after
,/Users/raddevon/.config/nvim/plugged/tern_for_vim/after,/Users/raddevon/.config/nvim/after', 'camelcase': 0, 'cwd': '/Users/raddevon/Documents/projects/resque/scheduler', 'ignorecase': 1, '
rpc': 'deoplete_auto_completion_begin', 'bufnr': 3, 'encoding': 'utf-8', 'start_complete': '\udc80\udcfdR()', 'smartcase': 1, 'vars': {'deoplete#auto_refresh_delay': 50, 'deoplete#_omni_patt
erns': {'xhtml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'xml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'mkd': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'html': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'markdown': ['<', '
<[^>]*\\s[[:alnum:]-]*']}, 'deoplete#enable_ignore_case': 1, 'deoplete#_channel_id': 4, 'deoplete#_neovim_python_version': ['0.1.9'], 'deoplete#disable_auto_complete': 0, 'deoplete#omni#func
tions': {}, 'deoplete#auto_complete_start_length': 2, 'deoplete#enable_refresh_always': 0, 'deoplete#max_menu_width': 40, 'deoplete#ignore_sources': {}, 'deoplete#auto_complete_delay': 150,
'deoplete#enable_smart_case': 1, 'deoplete#keyword_patterns': {}, 'deoplete#_saved_completeopt': 'menu,preview', 'deoplete#enable_profile': 0, 'deoplete#_keyword_patterns': {'_': '[a-zA-Z_]\
\k*'}, 'deoplete#_rank': {}, 'deoplete#delimiters': ['/', '.', '::', ':', '#'], 'deoplete#_context': {'refresh': 0, 'position': [0, 9, 6, 0]}, 'deoplete#omni_patterns': {}, 'deoplete#max_lis
t': 100, 'deoplete#member#prefix_patterns': {}, 'deoplete#omni#input_patterns': {}, 'deoplete#enable_at_startup': 1, 'deoplete#enable_camel_case': 0, 'deoplete#sources': {}, 'deoplete#max_ab
br_width': 80}, 'event': 'TextChangedI', 'max_abbr_width': 126, 'max_menu_width': 126, 'delay': 150, 'complete_str': ''}]'
Traceback (most recent call last):
  File "/Users/raddevon/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 52, in completion_begin
    self._deoplete.completion_begin(context)
  File "/Users/raddevon/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 50, in completion_begin
    self._vim.call('deoplete#mapping#_restore_completeopt')
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/neovim/api/nvim.py", line 213, in call
    return self.request('vim_call_function', name, args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/neovim/api/nvim.py", line 129, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Error calling function.'
```

**Comment by wsdjeg** [comment]
I can not understand, maybe you should update rplugin.

**Comment by Shougo** [comment]
You must execute `:UpdateRemotePlugins` command.

**Comment by raddevon** [comment]
Thanks for the reply. I did not try `:UpdateRemotePlugins`, but I was able to fix it by uninstalling and reinstalling deoplete.

**Comment by wsdjeg** [comment]
Nice.
