### ISSUE TITLE
<SNR>208_vim_oneshot_handler error on writing cpp

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#2836]
## can't write cpp 

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function <SNR>208_vim_oneshot_handler[6]..completor#action#callback[1]..completor#utils#on_data:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ccc/.cache/vimfiles/repos/github.com/maralla/completor.vim/pythonx/completor/api.py", line 14, in wrapper
    return func(vim.bindeval('a:'))
  File "/home/ccc/.cache/vimfiles/repos/github.com/maralla/completor.vim/pythonx/completor/api.py", line 44, in on_data
    return c.on_data(args['action'], args['msg']) if c else []
  File "/home/ccc/.cache/vimfiles/repos/github.com/maralla/completor.vim/pythonx/completor/__init__.py", line 239, in on_data
    return self.do_complete(data)
  File "/home/ccc/.cache/vimfiles/repos/github.com/maralla/completor.vim/pythonx/completor/__init__.py", line 199, in do_complete
    ret.extend(self.on_complete(data))
  File "/home/ccc/.cache/vimfiles/repos/github.com/maralla/completor.vim/pythonx/completers/cpp/__init__.py", line 230, in on_complete
    data['word'] = get_word(parts[2])
  File "/home/ccc/.cache/vimfiles/repos/github.com/maralla/completor.vim/pythonx/completers/cpp/__init__.py", line 52, in get_word
    parts = re.split(r'[ (\[{<]', text, 1)
  File "/usr/lib/python3.7/re.py", line 213, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object
Error detected while processing function <SNR>208_vim_oneshot_handler[6]..completor#action#callback[2]..completor#action#trigger[6]..<SNR>188_trigger_complete:
line    7:
E474: Invalid argument
Error detected while processing function <SNR>208_vim_oneshot_handler[6]..completor#action#callback[2]..completor#action#trigger:
line    6:
E171: Missing :endif
```

## Screenshots

https://asciinema.org/a/GDXmwG6TExpiCZwVAwyMtttnu

**Comment by wsdjeg** [comment]
I think it is bug of upstram plugin, https://github.com/maralla/completor.vim
