### ISSUE TITLE
Neomake: pylint: unexpected output on stderr: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Double1996** [wsdjeg/SpaceVim#809]
## Environment Information
- OS: mac os 
- neovim version: NVIM v0.2.0
- python: 3.5

## The reproduce ways from Vim starting (Required!)
 When I coding Python, I had installed **pylint** with pip  

## message with nvim
Neomake: pylint: unexpected output on stderr: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/functools.py", line 718, in dispatch
    impl = dispatch_cache[cls]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/weakref.py", line 352, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x103209138; to 'EnumMeta' at 0x1005a3d98 (Context)>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/functools.py", line 721, in dispatch
    impl = registry[cls]
KeyError: <enum 'Context'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pylint/lint.py", line 1220, in __init__
    linter.load_default_plugins()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pylint/lint.py", line 453, in load_default_plugins
    checkers.initialize(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pylint/checkers/__init__.py", line 114, in initialize
    register_plugins(linter, __path__[0])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pylint/utils.py", line 992, in register_plugins
    module = modutils.load_module_from_file(join(directory, filename))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astroid/modutils.py", line 272, in load_module_from_file
    return load_module_from_modpath(modpath, path, use_sys)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astroid/modutils.py", line 233, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pylint/checkers/python3.py", line 100, in <module>
    class Python3Checker(checkers.BaseChecker):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pylint/checkers/python3.py", line 501, in Python3Checker
    'sys.version_info < (3, 0)',
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pylint/checkers/python3.py", line 496, in <listcomp>
    [astroid.extract_node(x).repr_tree() for x in [
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astroid/node_classes.py", line 624, in repr_tree
    _repr_tree(self, result, set())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
# Neovimmake info
##### Enabled makers
For the current filetype ("python", used with :Neomake):
 - python
   - args: ['/Users/double2/.cache/vimfiles/repos/github.com/neomake/neomake/autoload/neomake/makers/ft/python/compile.py']
   - auto_enabled: 1
   - errorformat: '%E%f:%l:%c: %m'
   - exe: 'python'
   - output_stream: 'stdout'
   - serialize: 1
   - serialize_abort_on_error: 1
 - frosted
   - args: ['-vb']
   - auto_enabled: 1
   - errorformat: '%f:%l:%c:%m,%E%f:%l: %m,%-Z%p^,%-G%.%#'
   - exe: 'frosted'
   - WARNINGS:
   - errorformat: '%f:%l:%c:%m,%E%f:%l: %m,%-Z%p^,%-G%.%#'
   - exe: 'frosted'
   - WARNINGS:
     - maker's exe (frosted) is not executable.
 - pyflakes
   - args: []
   - auto_enabled: 1
   - errorformat: '%E%f:%l: could not compile,%-Z%p^,%E%f:%l:%c: %m,%E%f:%l: %m,%-G%.%#'
   - exe: 'pyflakes'
   - WARNINGS:
     - maker's exe (pyflakes) is not executable.
 - pycodestyle
   - args: []
   - auto_enabled: 1
   - errorformat: '%f:%l:%c: %m'
   - exe: 'pycodestyle'
   - postprocess: function('neomake#makers#ft#python#Pep8EntryProcess')
 - pydocstyle
   - args: []
   - auto_enabled: 1
   - errorformat: '%W%f:%l %.%#:,%+C        %m'
   - exe: 'pep257'
   - postprocess: function('neomake#utils#CompressWhitespace')
   - WARNINGS:
     - maker's exe (pep257) is not executable.
 - pylint
   - args: ['--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg} [{msg_id}]"', '--reports=no']
   - auto_enabled: 1
   - errorformat: '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#'
   - exe: 'pylint'
   - output_stream: 'stdout'
   - postprocess: [function('neomake#postprocess#GenericLengthPostprocess'), function('neomake#makers#ft#python#PylintEntryProcess')]
NOTE: you can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).

**Comment by wsdjeg** [comment]
#### Neomake information (use ":verbose NeomakeInfo" extra output)
##### Enabled makers
For the current filetype ("python", used with :Neomake):
 - python
   - args: ['/home/wsdjeg/.cache/vimfiles/repos/github.com/neomake/neomake/autoload/neomake/makers/ft/python/compile.py']
   - auto_enabled: 1
   - errorformat: '%E%f:%l:%c: %m'
   - exe: 'python'
   - output_stream: 'stdout'
   - serialize: 1
   - serialize_abort_on_error: 1
 - frosted
   - args: ['-vb']
   - auto_enabled: 1
   - errorformat: '%f:%l:%c:%m,%E%f:%l: %m,%-Z%p^,%-G%.%#'
   - exe: 'frosted'
   - WARNINGS:
     - maker's exe (frosted) is not executable.
 - pyflakes
   - args: []
   - auto_enabled: 1
   - errorformat: '%E%f:%l: could not compile,%-Z%p^,%E%f:%l:%c: %m,%E%f:%l: %m,%-G%.%#'
   - exe: 'pyflakes'
   - WARNINGS:
     - maker's exe (pyflakes) is not executable.
 - pycodestyle
   - args: []
   - auto_enabled: 1
   - errorformat: '%f:%l:%c: %m'
   - exe: 'pep8'
   - postprocess: function('neomake#makers#ft#python#Pep8EntryProcess')
   - WARNINGS:
     - maker's exe (pep8) is not executable.
 - pydocstyle
   - args: []
   - auto_enabled: 1
   - errorformat: '%W%f:%l %.%#:,%+C        %m'
   - exe: 'pep257'
   - postprocess: function('neomake#utils#CompressWhitespace')
   - WARNINGS:
     - maker's exe (pep257) is not executable.
 - pylint
   - args: ['--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg} [{msg_id}]"', '--reports=no']
   - auto_enabled: 1
   - errorformat: '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#'
   - exe: 'pylint'
   - output_stream: 'stdout'
   - postprocess: [function('neomake#postprocess#GenericLengthPostprocess'), function('neomake#makers#ft#python#PylintEntryProcess')]
   - WARNINGS:
     - maker's exe (pylint) is not executable.
NOTE: you can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).


For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.


Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1


##### Settings
```
g:neomake_cpp_clang_args = ['-std=c++11']
g:neomake_cpp_enabled_makers = ['clang']
g:neomake_error_sign = {'texthl': 'GruvboxRedSign', 'text': '✖'}
g:neomake_java_javac_delete_output = 0
g:neomake_open_list = 0
g:neomake_place_signs = 1
g:neomake_verbose = 0
g:neomake_vim_enabled_makers = ['vimlint', 'vint']
g:neomake_warning_sign = {'texthl': 'GruvboxYellowSign', 'text': '⚠'}
```

**Comment by wsdjeg** [comment]
@blueyed I am sorry for taking your time for this issue, in SpaceVim we use all most default setting of neomake, but as the user shown above, he still get this issue about pylint, I am not sure if this is a issue about neomake, because I can not reprodue it in my environment.

@Double1996 how do you install neovim, and neovim's python client? BTW how many different versions of python have installed?

**Comment by blueyed** [comment]
The problem is that pylint crashes.

@Double1996 
Can you run pylint manually (from the same dir and on the same file) without an issue?

**Comment by wsdjeg** [comment]
feel free to reopen!
