### ISSUE TITLE
After update all plugin, Neovim did not start

### ISSUE THREAD

**Issue by duytrung** [wsdjeg/SpaceVim#967]
## Environment Information
- OS: Windows 10
- vim version:
- neovim version: 0.2.1-1125

## The reproduce ways from Vim starting (Required!)

Nvim did not start after updating all plugins, using Spacevim 0.5.0 dev

## Output of the ':SPDebugInfo!'

Nvim did not run properly so SPDebugInfo was not generated

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

```
> nvim
function rtags#InitPython[9]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 1 was closed by the client
Traceback (most recent call last):^M
  File "<string>", line 1, in <module>^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\__init__.py", line 70, in start_host^M
    session = stdio_session()^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 37, in stdio_session^M
    return session('stdio')^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 18, in session^M
    loop = EventLoop(transport_type, *args, **kwargs)^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\event_loop\base.py", line 88, in __init__^M
    getattr(self, '_connect_{}'.format(transport_type))(*args)^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 93, in _connect_stdio^M
    self._loop.run_until_complete(coroutine)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 467, in run_until_complete^M
    return future.result()^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 1115, in connect_write_pipe^M
    transport = self._make_write_pipe_transport(pipe, protocol, waiter)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 424, in _make_write_pipe_transport^M
    sock, protocol, waiter, extra)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 317, in __init__^M
    self._read_fut = self._loop._proactor.recv(self._sock, 16)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\windows_events.py", line 430, in recv^M
    self._register_with_iocp(conn)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\windows_events.py", line 611, in _register_with_iocp^M
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)^M
OSError: [WinError 6] The handle is invalid^M
Exception ignored in: <bound method _ProactorBasePipeTransport.__del__ of <_ProactorWritePipeTransport closing fd=1>>^M
Traceback (most recent call last):^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 97, in __del__^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 84, in close^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 574, in call_soon^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 357, in _check_closed^M
RuntimeError: Event loop is closed^M
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
Press ENTER or type command to continue

```
Python 3.6.3 by Anaconda

**Comment by wsdjeg** [comment]
fixed.

**Comment by dbrw** [comment]
how did you fix this?

**Comment by wsdjeg** [comment]
just make rtags lazy loaded on_if has +python.
